/*
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 */
package zowe.client.sdk.zosmfworkflow.response;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * API response for list archived workflows.
 * <p>
 * <a href="https://www.ibm.com/docs/en/zos/3.2.0?topic=services-list-archived-workflows-system">z/OSMF REST API</a>
 *
 * @author Muhammad Imran
 * @version 7.0
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class WorkflowArchivedResponse {

    /**
     * Descriptive name for the workflow.
     */
    private final String name;

    /**
     * Workflow key. A string value, generated by z/OSMF to uniquely identify the workflow instance.
     */
    private final String key;

    /**
     * Workflow instance URI path, which you can use to retrieve information about the archived workflow.
     */
    private final String archivedInstanceURI;

    /**
     * WorkflowArchivedResponse Jackson constructor.
     *
     * @param name                workflow name
     * @param key                 workflow key
     * @param archivedInstanceURI workflow instance URI path
     */
    @JsonCreator
    public WorkflowArchivedResponse(
            @JsonProperty("workflowName") final String name,
            @JsonProperty("workflowKey") final String key,
            @JsonProperty("archivedInstanceURI") final String archivedInstanceURI) {
        this.name = name == null ? "" : name;
        this.key = key == null ? "" : key;
        this.archivedInstanceURI = archivedInstanceURI == null ? "" : archivedInstanceURI;
    }

    /**
     * Retrieve name value.
     *
     * @return name value
     */
    public String getName() {
        return name;
    }

    /**
     * Retrieve key value.
     *
     * @return key value
     */
    public String getKey() {
        return key;
    }

    /**
     * Retrieve archivedInstanceURI value.
     *
     * @return archivedInstanceURI value
     */
    public String getArchivedInstanceURI() {
        return archivedInstanceURI;
    }

    /**
     * Return a string value representing a WorkflowArchivedResponse object.
     *
     * @return string representation of WorkflowArchivedResponse
     */
    @Override
    public String toString() {
        return "WorkflowArchivedResponse{" +
                "name='" + name + '\'' +
                ", key='" + key + '\'' +
                ", archivedInstanceURI='" + archivedInstanceURI + '\'' +
                '}';
    }

}
