/*
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 */
package zowe.client.sdk.zosmfworkflow.response;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import zowe.client.sdk.zosmfworkflow.model.WorkflowAutomationStatus;

/**
 * API response for list workflows.
 * <p>
 * <a href="https://www.ibm.com/docs/en/zos/3.2.0?topic=services-list-workflows-system-sysplex">z/OSMF REST API</a>
 *
 * @author Jorge Samaniego
 * @version 7.0
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class WorkflowListResponse {

    /**
     * Descriptive name for the workflow.
     */
    private final String workflowName;

    /**
     * Workflow key. A string value, generated by z/OSMF to uniquely identify the workflow instance.
     */
    private final String workflowKey;

    /**
     * Description of the workflow.
     */
    private final String workflowDescription;

    /**
     * Workflow ID. A short, arbitrary value that identifies the workflow.
     */
    private final String workflowID;

    /**
     * Version of the workflow definition file.
     */
    private final String workflowVersion;

    /**
     * The 128-bit hash value associated with the workflow definition file used to create the workflow.
     */
    private final String workflowDefinitionFileMD5Value;

    /**
     * Name of the vendor that provided the workflow definition file.
     */
    private final String vendor;

    /**
     * User ID of the workflow owner.
     */
    private final String owner;

    /**
     * Full name of the z/OS system on which the workflow is to be performed (sysplex.sysname).
     */
    private final String system;

    /**
     * Category of the workflow, which is general, configuration, or provisioning.
     */
    private final String category;

    /**
     * Identifier of the product or component that is being configured through the workflow.
     */
    private final String productID;

    /**
     * Name of the product or component that is being configured through the workflow.
     */
    private final String productName;

    /**
     * Version and release of the product or component that is configured through the workflow.
     */
    private final String productVersion;

    /**
     * Percentage of the workflow that is completed.
     */
    private final Integer percentComplete;

    /**
     * Indicates whether a workflow is eligible to be called by another workflow.
     */
    private final Boolean isCallable;

    /**
     * Indicates whether the automation ready steps can be run in parallel.
     */
    private final Boolean containsParallelSteps;

    /**
     * Restricts a workflow to one instance only (system, sysplex, or none).
     */
    private final String scope;

    /**
     * Indicates the current workflow status.
     */
    private final String statusName;

    /**
     * For a workflow that submits a job, indicates whether the job is deleted from the JES spool when complete.
     */
    private final Boolean deleteCompletedJobs;

    /**
     * An automation-info object containing details about the most recent start automation request.
     */
    private final WorkflowAutomationStatus automationStatus;

    /**
     * Specifies the access type for the workflow (Public, Restricted, or Private).
     */
    private final String access;

    /**
     * For a workflow that submits a job, the account information to use in the JCL JOB statement.
     */
    private final String accountInfo;

    /**
     * For a workflow that submits a job, the JOB statement JCL that is used in the job.
     */
    private final String jobStatement;

    /**
     * Global variable group for the workflow.
     */
    private final String globalVariableGroup;

    /**
     * WorkflowListResponse Jackson constructor.
     *
     * @param workflowName                   descriptive name for the workflow
     * @param workflowKey                    workflow key
     * @param workflowDescription            description of the workflow
     * @param workflowID                     workflow id
     * @param workflowVersion                version of the workflow definition file
     * @param workflowDefinitionFileMD5Value hash value of the workflow definition file
     * @param vendor                         vendor name
     * @param owner                          user ID of the workflow owner
     * @param system                         full name of the z/OS system
     * @param category                       category of the workflow
     * @param productID                      identifier of the product being configured
     * @param productName                    name of the product being configured
     * @param productVersion                 version of the product being configured
     * @param percentComplete                percentage of the workflow that is completed
     * @param isCallable                     indicates whether the workflow can be called by another workflow
     * @param containsParallelSteps          indicates whether automation ready steps can run in parallel
     * @param scope                          singleton scope for the workflow
     * @param statusName                     current workflow status
     * @param deleteCompletedJobs            indicates whether jobs are deleted from the JES spool when complete
     * @param automationStatus               details about the most recent start automation request
     * @param access                         access type for the workflow
     * @param accountInfo                    account information for the JCL JOB statement
     * @param jobStatement                   JOB statement JCL used in the job
     * @param globalVariableGroup            global variable group for the workflow
     */
    @JsonCreator
    public WorkflowListResponse(
            @JsonProperty("workflowName") final String workflowName,
            @JsonProperty("workflowKey") final String workflowKey,
            @JsonProperty("workflowDescription") final String workflowDescription,
            @JsonProperty("workflowID") final String workflowID,
            @JsonProperty("workflowVersion") final String workflowVersion,
            @JsonProperty("workflowDefinitionFileMD5Value") final String workflowDefinitionFileMD5Value,
            @JsonProperty("vendor") final String vendor,
            @JsonProperty("owner") final String owner,
            @JsonProperty("system") final String system,
            @JsonProperty("category") final String category,
            @JsonProperty("productID") final String productID,
            @JsonProperty("productName") final String productName,
            @JsonProperty("productVersion") final String productVersion,
            @JsonProperty("percentComplete") final Integer percentComplete,
            @JsonProperty("isCallable") final Boolean isCallable,
            @JsonProperty("containsParallelSteps") final Boolean containsParallelSteps,
            @JsonProperty("scope") final String scope,
            @JsonProperty("statusName") final String statusName,
            @JsonProperty("deleteCompletedJobs") final Boolean deleteCompletedJobs,
            @JsonProperty("automationStatus") final WorkflowAutomationStatus automationStatus,
            @JsonProperty("access") final String access,
            @JsonProperty("accountInfo") final String accountInfo,
            @JsonProperty("jobStatement") final String jobStatement,
            @JsonProperty("globalVariableGroup") final String globalVariableGroup) {
        this.workflowName = orEmpty(workflowName);
        this.workflowKey = orEmpty(workflowKey);
        this.workflowDescription = orEmpty(workflowDescription);
        this.workflowID = orEmpty(workflowID);
        this.workflowVersion = orEmpty(workflowVersion);
        this.workflowDefinitionFileMD5Value = orEmpty(workflowDefinitionFileMD5Value);
        this.vendor = orEmpty(vendor);
        this.owner = orEmpty(owner);
        this.system = orEmpty(system);
        this.category = orEmpty(category);
        this.productID = orEmpty(productID);
        this.productName = orEmpty(productName);
        this.productVersion = orEmpty(productVersion);
        this.percentComplete = percentComplete;
        this.isCallable = isCallable;
        this.containsParallelSteps = containsParallelSteps;
        this.scope = orEmpty(scope);
        this.statusName = orEmpty(statusName);
        this.deleteCompletedJobs = deleteCompletedJobs;
        this.automationStatus = automationStatus;
        this.access = orEmpty(access);
        this.accountInfo = orEmpty(accountInfo);
        this.jobStatement = orEmpty(jobStatement);
        this.globalVariableGroup = orEmpty(globalVariableGroup);
    }

    /* Null-handling helpers */

    private static String orEmpty(final String value) {
        return value == null ? "" : value;
    }

    /**
     * Retrieve workflowName value.
     *
     * @return workflowName value
     */
    public String getWorkflowName() {
        return workflowName;
    }

    /**
     * Retrieve workflowKey value.
     *
     * @return workflowKey value
     */
    public String getWorkflowKey() {
        return workflowKey;
    }

    /**
     * Retrieve workflowDescription value.
     *
     * @return workflowDescription value
     */
    public String getWorkflowDescription() {
        return workflowDescription;
    }

    /**
     * Retrieve workflowID value.
     *
     * @return workflowID value
     */
    public String getWorkflowID() {
        return workflowID;
    }

    /**
     * Retrieve workflowVersion value.
     *
     * @return workflowVersion value
     */
    public String getWorkflowVersion() {
        return workflowVersion;
    }

    /**
     * Retrieve workflowDefinitionFileMD5Value value.
     *
     * @return workflowDefinitionFileMD5Value value
     */
    public String getWorkflowDefinitionFileMD5Value() {
        return workflowDefinitionFileMD5Value;
    }

    /**
     * Retrieve vendor value.
     *
     * @return vendor value
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * Retrieve owner value.
     *
     * @return owner value
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Retrieve system value.
     *
     * @return system value
     */
    public String getSystem() {
        return system;
    }

    /**
     * Retrieve category value.
     *
     * @return category value
     */
    public String getCategory() {
        return category;
    }

    /**
     * Retrieve productID value.
     *
     * @return productID value
     */
    public String getProductID() {
        return productID;
    }

    /**
     * Retrieve productName value.
     *
     * @return productName value
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Retrieve productVersion value.
     *
     * @return productVersion value
     */
    public String getProductVersion() {
        return productVersion;
    }

    /**
     * Retrieve percentComplete value.
     *
     * @return percentComplete value
     */
    public Integer getPercentComplete() {
        return percentComplete;
    }

    /**
     * Retrieve isCallable value.
     *
     * @return isCallable value
     */
    public Boolean getIsCallable() {
        return isCallable;
    }

    /**
     * Retrieve containsParallelSteps value.
     *
     * @return containsParallelSteps value
     */
    public Boolean getContainsParallelSteps() {
        return containsParallelSteps;
    }

    /**
     * Retrieve scope value.
     *
     * @return scope value
     */
    public String getScope() {
        return scope;
    }

    /**
     * Retrieve statusName value.
     *
     * @return statusName value
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * Retrieve deleteCompletedJobs value.
     *
     * @return deleteCompletedJobs value
     */
    public Boolean getDeleteCompletedJobs() {
        return deleteCompletedJobs;
    }

    /**
     * Retrieve automationStatus value.
     *
     * @return automationStatus value
     */
    public WorkflowAutomationStatus getAutomationStatus() {
        return automationStatus;
    }

    /**
     * Retrieve access value.
     *
     * @return access value
     */
    public String getAccess() {
        return access;
    }

    /**
     * Retrieve accountInfo value.
     *
     * @return accountInfo value
     */
    public String getAccountInfo() {
        return accountInfo;
    }

    /**
     * Retrieve jobStatement value.
     *
     * @return jobStatement value
     */
    public String getJobStatement() {
        return jobStatement;
    }

    /**
     * Retrieve globalVariableGroup value.
     *
     * @return globalVariableGroup value
     */
    public String getGlobalVariableGroup() {
        return globalVariableGroup;
    }

    /**
     * Return a string value representing a WorkflowListResponse object.
     *
     * @return string representation of WorkflowListResponse
     */
    @Override
    public String toString() {
        return "WorkflowListResponse{" +
                "workflowName='" + workflowName + '\'' +
                ", workflowKey='" + workflowKey + '\'' +
                ", workflowDescription='" + workflowDescription + '\'' +
                ", workflowID='" + workflowID + '\'' +
                ", workflowVersion='" + workflowVersion + '\'' +
                ", workflowDefinitionFileMD5Value='" + workflowDefinitionFileMD5Value + '\'' +
                ", vendor='" + vendor + '\'' +
                ", owner='" + owner + '\'' +
                ", system='" + system + '\'' +
                ", category='" + category + '\'' +
                ", productID='" + productID + '\'' +
                ", productName='" + productName + '\'' +
                ", productVersion='" + productVersion + '\'' +
                ", percentComplete=" + percentComplete +
                ", isCallable=" + isCallable +
                ", containsParallelSteps=" + containsParallelSteps +
                ", scope='" + scope + '\'' +
                ", statusName='" + statusName + '\'' +
                ", deleteCompletedJobs=" + deleteCompletedJobs +
                ", automationStatus=" + automationStatus +
                ", access='" + access + '\'' +
                ", accountInfo='" + accountInfo + '\'' +
                ", jobStatement='" + jobStatement + '\'' +
                ", globalVariableGroup='" + globalVariableGroup + '\'' +
                '}';
    }

}