/*
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 */
package zowe.client.sdk.zosmfworkflow.response;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * API response for list workflows; represents a workflow-info object.
 * <p>
 * <a href="https://www.ibm.com/docs/en/zos/3.2.0?topic=services-list-workflows-system-sysplex">z/OSMF REST API</a>
 *
 * @author Ashish Kumar Dash
 * @version 7.0
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class WorkflowListResponse {

    /**
     * Descriptive name for the workflow.
     */
    private final String workflowName;

    /**
     * Workflow key. A string value, generated by z/OSMF to uniquely identify the workflow instance.
     */
    private final String workflowKey;

    /**
     * Description of the workflow.
     */
    private final String workflowDescription;

    /**
     * Workflow ID. A short, arbitrary value that identifies the workflow.
     */
    private final String workflowID;

    /**
     * Version of the workflow definition file.
     */
    private final String workflowVersion;

    /**
     * The 128-bit hash value associated with the workflow definition file used to create the workflow.
     */
    private final String workflowDefinitionFileMD5Value;

    /**
     * Workflow instance URI path, which you can use to retrieve information about the workflow.
     */
    private final String instanceURI;

    /**
     * User ID of the workflow owner.
     */
    private final String owner;

    /**
     * Name of the vendor that provided the workflow definition file.
     */
    private final String vendor;

    /**
     * Access type for the workflow, which is either Public, Restricted or Private.
     */
    private final String access;

    /**
     * WorkflowListResponse Jackson constructor.
     *
     * @param workflowName                   workflow name
     * @param workflowKey                    workflow key
     * @param workflowDescription            workflow description
     * @param workflowID                     workflow ID
     * @param workflowVersion                workflow definition file version
     * @param workflowDefinitionFileMD5Value workflow definition file hash value
     * @param instanceURI                    workflow instance URI path
     * @param owner                          workflow owner
     * @param vendor                         workflow definition file vendor
     * @param access                         workflow access type
     */
    @JsonCreator
    public WorkflowListResponse(
            @JsonProperty("workflowName") final String workflowName,
            @JsonProperty("workflowKey") final String workflowKey,
            @JsonProperty("workflowDescription") final String workflowDescription,
            @JsonProperty("workflowID") final String workflowID,
            @JsonProperty("workflowVersion") final String workflowVersion,
            @JsonProperty("workflowDefinitionFileMD5Value") final String workflowDefinitionFileMD5Value,
            @JsonProperty("instanceURI") final String instanceURI,
            @JsonProperty("owner") final String owner,
            @JsonProperty("vendor") final String vendor,
            @JsonProperty("access") final String access) {
        this.workflowName = workflowName == null ? "" : workflowName;
        this.workflowKey = workflowKey == null ? "" : workflowKey;
        this.workflowDescription = workflowDescription == null ? "" : workflowDescription;
        this.workflowID = workflowID == null ? "" : workflowID;
        this.workflowVersion = workflowVersion == null ? "" : workflowVersion;
        this.workflowDefinitionFileMD5Value =
                workflowDefinitionFileMD5Value == null ? "" : workflowDefinitionFileMD5Value;
        this.instanceURI = instanceURI == null ? "" : instanceURI;
        this.owner = owner == null ? "" : owner;
        this.vendor = vendor == null ? "" : vendor;
        this.access = access == null ? "" : access;
    }

    /**
     * Retrieve workflowName value.
     *
     * @return workflowName value
     */
    public String getWorkflowName() {
        return workflowName;
    }

    /**
     * Retrieve workflowKey value.
     *
     * @return workflowKey value
     */
    public String getWorkflowKey() {
        return workflowKey;
    }

    /**
     * Retrieve workflowDescription value.
     *
     * @return workflowDescription value
     */
    public String getWorkflowDescription() {
        return workflowDescription;
    }

    /**
     * Retrieve workflowID value.
     *
     * @return workflowID value
     */
    public String getWorkflowID() {
        return workflowID;
    }

    /**
     * Retrieve workflowVersion value.
     *
     * @return workflowVersion value
     */
    public String getWorkflowVersion() {
        return workflowVersion;
    }

    /**
     * Retrieve workflowDefinitionFileMD5Value value.
     *
     * @return workflowDefinitionFileMD5Value value
     */
    public String getWorkflowDefinitionFileMD5Value() {
        return workflowDefinitionFileMD5Value;
    }

    /**
     * Retrieve instanceURI value.
     *
     * @return instanceURI value
     */
    public String getInstanceURI() {
        return instanceURI;
    }

    /**
     * Retrieve owner value.
     *
     * @return owner value
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Retrieve vendor value.
     *
     * @return vendor value
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * Retrieve access value.
     *
     * @return access value
     */
    public String getAccess() {
        return access;
    }

    /**
     * Return a string value representing a WorkflowListResponse object.
     *
     * @return string representation of WorkflowListResponse
     */
    @Override
    public String toString() {
        return "WorkflowListResponse{" +
                "workflowName='" + workflowName + '\'' +
                ", workflowKey='" + workflowKey + '\'' +
                ", workflowDescription='" + workflowDescription + '\'' +
                ", workflowID='" + workflowID + '\'' +
                ", workflowVersion='" + workflowVersion + '\'' +
                ", workflowDefinitionFileMD5Value='" + workflowDefinitionFileMD5Value + '\'' +
                ", instanceURI='" + instanceURI + '\'' +
                ", owner='" + owner + '\'' +
                ", vendor='" + vendor + '\'' +
                ", access='" + access + '\'' +
                '}';
    }

}
