/*
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 */
package zowe.client.sdk.zosmfworkflow.response;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import zowe.client.sdk.zosmfworkflow.model.WorkflowAutomationStatus;
import zowe.client.sdk.zosmfworkflow.model.WorkflowStepInfo;
import zowe.client.sdk.zosmfworkflow.model.WorkflowVariableInfo;

import java.util.Collections;
import java.util.List;

/**
 * API response for get properties of a workflow.
 * <p>
 * <a href="https://www.ibm.com/docs/en/zos/3.2.0?topic=services-get-properties-workflow">z/OSMF REST API</a>
 *
 * @author Shantanu Danej
 * @version 7.0
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class WorkflowGetPropertiesResponse {

    /**
     * Descriptive name for the workflow.
     */
    private final String workflowName;

    /**
     * Workflow key. A string value, generated by z/OSMF to uniquely identify the workflow instance.
     */
    private final String workflowKey;

    /**
     * Description of the workflow.
     */
    private final String workflowDescription;

    /**
     * Workflow ID. A short, arbitrary value that identifies the workflow.
     */
    private final String workflowID;

    /**
     * Version of the workflow definition file.
     */
    private final String workflowVersion;

    /**
     * The 128-bit hash value associated with the workflow definition file used to create the workflow.
     */
    private final String workflowDefinitionFileMD5Value;

    /**
     * Name of the vendor that provided the workflow definition file.
     */
    private final String vendor;

    /**
     * User ID of the workflow owner.
     */
    private final String owner;

    /**
     * SAF ID who will own the archived workflow after a workflow is archived to a user specified directory.
     */
    private final String workflowArchiveSAFID;

    /**
     * Full name of the z/OS system on which the workflow is to be performed (sysplex.sysname).
     */
    private final String system;

    /**
     * Name of the UNIX directory that is used for automatically saving job spool files from the workflow.
     */
    private final String jobsOutputDirectory;

    /**
     * Category of the workflow, which is general, configuration, or provisioning.
     */
    private final String category;

    /**
     * Identifier of the product or component that is being configured through the workflow.
     */
    private final String productID;

    /**
     * Name of the product or component that is being configured through the workflow.
     */
    private final String productName;

    /**
     * Version and release of the product or component that is configured through the workflow.
     */
    private final String productVersion;

    /**
     * Percentage of the workflow that is completed.
     */
    private final Integer percentComplete;

    /**
     * Indicates whether a workflow is eligible to be called by another workflow.
     */
    private final Boolean isCallable;

    /**
     * Indicates whether the automation ready steps can be run in parallel.
     */
    private final Boolean containsParallelSteps;

    /**
     * Restricts a workflow to one instance only (system, sysplex, or none).
     */
    private final String scope;

    /**
     * Indicates the current workflow status.
     */
    private final String statusName;

    /**
     * For a workflow that submits a job, indicates whether the job is deleted from the JES spool when complete.
     */
    private final Boolean deleteCompletedJobs;

    /**
     * An automation-info object containing details about the most recent start automation request.
     */
    private final WorkflowAutomationStatus automationStatus;

    /**
     * Indicates whether the workflow is automatically deleted from the system after it completes successfully.
     */
    private final Boolean autoDeleteOnCompletion;

    /**
     * Specifies the access type for the workflow (Public, Restricted, or Private).
     */
    private final String access;

    /**
     * For a workflow that submits a job, the account information to use in the JCL JOB statement.
     */
    private final String accountInfo;

    /**
     * For a workflow that submits a job, the JOB statement JCL that is used in the job.
     */
    private final String jobStatement;

    /**
     * The unique identifier for the template (provisioning workflows only).
     */
    private final String templateID;

    /**
     * The action ID for the action object (provisioning workflows only).
     */
    private final String actionID;

    /**
     * The ID of the software services registry (provisioning workflows only).
     */
    private final String registryID;

    /**
     * The ID of the software instance parent registry entry (provisioning workflows only).
     */
    private final String parentRegistryID;

    /**
     * The ID of the domain that is associated with the template (provisioning workflows only).
     */
    private final String domainID;

    /**
     * The ID of the tenant that is associated with the resource pool (provisioning workflows only).
     */
    private final String tenantID;

    /**
     * The created software service instance name (provisioning workflows only).
     */
    private final String softwareServiceInstanceName;

    /**
     * The name of the template that is associated with the resource pool (provisioning workflows only).
     */
    private final String templateName;

    /**
     * Global variable group for the workflow.
     */
    private final String globalVariableGroup;

    /**
     * Indicates whether the simplified format is used for references to instance variables.
     */
    private final String isInstanceVariableWithoutPrefix;

    /**
     * Array of step-info objects, returned only when the steps attribute is requested.
     */
    private final List<WorkflowStepInfo> steps;

    /**
     * Array of variable-info objects, returned only when the variables attribute is requested.
     */
    private final List<WorkflowVariableInfo> variables;

    /**
     * WorkflowGetPropertiesResponse Jackson constructor.
     *
     * @param workflowName                    descriptive name for the workflow
     * @param workflowKey                     workflow key
     * @param workflowDescription             description of the workflow
     * @param workflowID                      workflow id
     * @param workflowVersion                 version of the workflow definition file
     * @param workflowDefinitionFileMD5Value  hash value of the workflow definition file
     * @param vendor                          vendor name
     * @param owner                           user ID of the workflow owner
     * @param workflowArchiveSAFID            SAF ID that will own the archived workflow
     * @param system                          full name of the z/OS system
     * @param jobsOutputDirectory             directory used for saving job spool files
     * @param category                        category of the workflow
     * @param productID                       identifier of the product being configured
     * @param productName                     name of the product being configured
     * @param productVersion                  version of the product being configured
     * @param percentComplete                 percentage of the workflow that is completed
     * @param isCallable                      indicates whether the workflow can be called by another workflow
     * @param containsParallelSteps           indicates whether automation ready steps can run in parallel
     * @param scope                           singleton scope for the workflow
     * @param statusName                      current workflow status
     * @param deleteCompletedJobs             indicates whether jobs are deleted from the JES spool when complete
     * @param automationStatus                details about the most recent start automation request
     * @param autoDeleteOnCompletion          indicates whether the workflow is deleted after it completes
     * @param access                          access type for the workflow
     * @param accountInfo                     account information for the JCL JOB statement
     * @param jobStatement                    JOB statement JCL used in the job
     * @param templateID                      unique identifier for the template
     * @param actionID                        action ID for the action object
     * @param registryID                      ID of the software services registry
     * @param parentRegistryID                ID of the software instance parent registry entry
     * @param domainID                        ID of the domain associated with the template
     * @param tenantID                        ID of the tenant associated with the resource pool
     * @param softwareServiceInstanceName     created software service instance name
     * @param templateName                    name of the template associated with the resource pool
     * @param globalVariableGroup             global variable group for the workflow
     * @param isInstanceVariableWithoutPrefix indicates whether the simplified instance variable format is used
     * @param steps                           array of step-info objects
     * @param variables                       array of variable-info objects
     */
    @JsonCreator
    public WorkflowGetPropertiesResponse(
            @JsonProperty("workflowName") final String workflowName,
            @JsonProperty("workflowKey") final String workflowKey,
            @JsonProperty("workflowDescription") final String workflowDescription,
            @JsonProperty("workflowID") final String workflowID,
            @JsonProperty("workflowVersion") final String workflowVersion,
            @JsonProperty("workflowDefinitionFileMD5Value") final String workflowDefinitionFileMD5Value,
            @JsonProperty("vendor") final String vendor,
            @JsonProperty("owner") final String owner,
            @JsonProperty("workflowArchiveSAFID") final String workflowArchiveSAFID,
            @JsonProperty("system") final String system,
            @JsonProperty("jobsOutputDirectory") final String jobsOutputDirectory,
            @JsonProperty("category") final String category,
            @JsonProperty("productID") final String productID,
            @JsonProperty("productName") final String productName,
            @JsonProperty("productVersion") final String productVersion,
            @JsonProperty("percentComplete") final Integer percentComplete,
            @JsonProperty("isCallable") final Boolean isCallable,
            @JsonProperty("containsParallelSteps") final Boolean containsParallelSteps,
            @JsonProperty("scope") final String scope,
            @JsonProperty("statusName") final String statusName,
            @JsonProperty("deleteCompletedJobs") final Boolean deleteCompletedJobs,
            @JsonProperty("automationStatus") final WorkflowAutomationStatus automationStatus,
            @JsonProperty("autoDeleteOnCompletion") final Boolean autoDeleteOnCompletion,
            @JsonProperty("access") final String access,
            @JsonProperty("accountInfo") final String accountInfo,
            @JsonProperty("jobStatement") final String jobStatement,
            @JsonProperty("templateID") final String templateID,
            @JsonProperty("actionID") final String actionID,
            @JsonProperty("registryID") final String registryID,
            @JsonProperty("parentRegistryID") final String parentRegistryID,
            @JsonProperty("domainID") final String domainID,
            @JsonProperty("tenantID") final String tenantID,
            @JsonProperty("software-service-instance-name") final String softwareServiceInstanceName,
            @JsonProperty("templateName") final String templateName,
            @JsonProperty("globalVariableGroup") final String globalVariableGroup,
            @JsonProperty("isInstanceVariableWithoutPrefix") final String isInstanceVariableWithoutPrefix,
            @JsonProperty("steps") final List<WorkflowStepInfo> steps,
            @JsonProperty("variables") final List<WorkflowVariableInfo> variables) {
        this.workflowName = orEmpty(workflowName);
        this.workflowKey = orEmpty(workflowKey);
        this.workflowDescription = orEmpty(workflowDescription);
        this.workflowID = orEmpty(workflowID);
        this.workflowVersion = orEmpty(workflowVersion);
        this.workflowDefinitionFileMD5Value = orEmpty(workflowDefinitionFileMD5Value);
        this.vendor = orEmpty(vendor);
        this.owner = orEmpty(owner);
        this.workflowArchiveSAFID = orEmpty(workflowArchiveSAFID);
        this.system = orEmpty(system);
        this.jobsOutputDirectory = orEmpty(jobsOutputDirectory);
        this.category = orEmpty(category);
        this.productID = orEmpty(productID);
        this.productName = orEmpty(productName);
        this.productVersion = orEmpty(productVersion);
        this.percentComplete = percentComplete;
        this.isCallable = isCallable;
        this.containsParallelSteps = containsParallelSteps;
        this.scope = orEmpty(scope);
        this.statusName = orEmpty(statusName);
        this.deleteCompletedJobs = deleteCompletedJobs;
        this.automationStatus = automationStatus;
        this.autoDeleteOnCompletion = autoDeleteOnCompletion;
        this.access = orEmpty(access);
        this.accountInfo = orEmpty(accountInfo);
        this.jobStatement = orEmpty(jobStatement);
        this.templateID = orEmpty(templateID);
        this.actionID = orEmpty(actionID);
        this.registryID = orEmpty(registryID);
        this.parentRegistryID = orEmpty(parentRegistryID);
        this.domainID = orEmpty(domainID);
        this.tenantID = orEmpty(tenantID);
        this.softwareServiceInstanceName = orEmpty(softwareServiceInstanceName);
        this.templateName = orEmpty(templateName);
        this.globalVariableGroup = orEmpty(globalVariableGroup);
        this.isInstanceVariableWithoutPrefix = orEmpty(isInstanceVariableWithoutPrefix);
        this.steps = orEmpty(steps);
        this.variables = orEmpty(variables);
    }

    /* Null-handling helpers */

    private static String orEmpty(final String value) {
        return value == null ? "" : value;
    }

    private static <T> List<T> orEmpty(final List<T> value) {
        return value == null ? Collections.emptyList() : value;
    }

    /**
     * Retrieve workflowName value.
     *
     * @return workflowName value
     */
    public String getWorkflowName() {
        return workflowName;
    }

    /**
     * Retrieve workflowKey value.
     *
     * @return workflowKey value
     */
    public String getWorkflowKey() {
        return workflowKey;
    }

    /**
     * Retrieve workflowDescription value.
     *
     * @return workflowDescription value
     */
    public String getWorkflowDescription() {
        return workflowDescription;
    }

    /**
     * Retrieve workflowID value.
     *
     * @return workflowID value
     */
    public String getWorkflowID() {
        return workflowID;
    }

    /**
     * Retrieve workflowVersion value.
     *
     * @return workflowVersion value
     */
    public String getWorkflowVersion() {
        return workflowVersion;
    }

    /**
     * Retrieve workflowDefinitionFileMD5Value value.
     *
     * @return workflowDefinitionFileMD5Value value
     */
    public String getWorkflowDefinitionFileMD5Value() {
        return workflowDefinitionFileMD5Value;
    }

    /**
     * Retrieve vendor value.
     *
     * @return vendor value
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * Retrieve owner value.
     *
     * @return owner value
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Retrieve workflowArchiveSAFID value.
     *
     * @return workflowArchiveSAFID value
     */
    public String getWorkflowArchiveSAFID() {
        return workflowArchiveSAFID;
    }

    /**
     * Retrieve system value.
     *
     * @return system value
     */
    public String getSystem() {
        return system;
    }

    /**
     * Retrieve jobsOutputDirectory value.
     *
     * @return jobsOutputDirectory value
     */
    public String getJobsOutputDirectory() {
        return jobsOutputDirectory;
    }

    /**
     * Retrieve category value.
     *
     * @return category value
     */
    public String getCategory() {
        return category;
    }

    /**
     * Retrieve productID value.
     *
     * @return productID value
     */
    public String getProductID() {
        return productID;
    }

    /**
     * Retrieve productName value.
     *
     * @return productName value
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Retrieve productVersion value.
     *
     * @return productVersion value
     */
    public String getProductVersion() {
        return productVersion;
    }

    /**
     * Retrieve percentComplete value.
     *
     * @return percentComplete value
     */
    public Integer getPercentComplete() {
        return percentComplete;
    }

    /**
     * Retrieve isCallable value.
     *
     * @return isCallable value
     */
    public Boolean getIsCallable() {
        return isCallable;
    }

    /**
     * Retrieve containsParallelSteps value.
     *
     * @return containsParallelSteps value
     */
    public Boolean getContainsParallelSteps() {
        return containsParallelSteps;
    }

    /**
     * Retrieve scope value.
     *
     * @return scope value
     */
    public String getScope() {
        return scope;
    }

    /**
     * Retrieve statusName value.
     *
     * @return statusName value
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * Retrieve deleteCompletedJobs value.
     *
     * @return deleteCompletedJobs value
     */
    public Boolean getDeleteCompletedJobs() {
        return deleteCompletedJobs;
    }

    /**
     * Retrieve automationStatus value.
     *
     * @return automationStatus value
     */
    public WorkflowAutomationStatus getAutomationStatus() {
        return automationStatus;
    }

    /**
     * Retrieve autoDeleteOnCompletion value.
     *
     * @return autoDeleteOnCompletion value
     */
    public Boolean getAutoDeleteOnCompletion() {
        return autoDeleteOnCompletion;
    }

    /**
     * Retrieve access value.
     *
     * @return access value
     */
    public String getAccess() {
        return access;
    }

    /**
     * Retrieve accountInfo value.
     *
     * @return accountInfo value
     */
    public String getAccountInfo() {
        return accountInfo;
    }

    /**
     * Retrieve jobStatement value.
     *
     * @return jobStatement value
     */
    public String getJobStatement() {
        return jobStatement;
    }

    /**
     * Retrieve templateID value.
     *
     * @return templateID value
     */
    public String getTemplateID() {
        return templateID;
    }

    /**
     * Retrieve actionID value.
     *
     * @return actionID value
     */
    public String getActionID() {
        return actionID;
    }

    /**
     * Retrieve registryID value.
     *
     * @return registryID value
     */
    public String getRegistryID() {
        return registryID;
    }

    /**
     * Retrieve parentRegistryID value.
     *
     * @return parentRegistryID value
     */
    public String getParentRegistryID() {
        return parentRegistryID;
    }

    /**
     * Retrieve domainID value.
     *
     * @return domainID value
     */
    public String getDomainID() {
        return domainID;
    }

    /**
     * Retrieve tenantID value.
     *
     * @return tenantID value
     */
    public String getTenantID() {
        return tenantID;
    }

    /**
     * Retrieve softwareServiceInstanceName value.
     *
     * @return softwareServiceInstanceName value
     */
    public String getSoftwareServiceInstanceName() {
        return softwareServiceInstanceName;
    }

    /**
     * Retrieve templateName value.
     *
     * @return templateName value
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * Retrieve globalVariableGroup value.
     *
     * @return globalVariableGroup value
     */
    public String getGlobalVariableGroup() {
        return globalVariableGroup;
    }

    /**
     * Retrieve isInstanceVariableWithoutPrefix value.
     *
     * @return isInstanceVariableWithoutPrefix value
     */
    public String getIsInstanceVariableWithoutPrefix() {
        return isInstanceVariableWithoutPrefix;
    }

    /**
     * Retrieve steps value.
     *
     * @return steps value
     */
    public List<WorkflowStepInfo> getSteps() {
        return steps;
    }

    /**
     * Retrieve variables value.
     *
     * @return variables value
     */
    public List<WorkflowVariableInfo> getVariables() {
        return variables;
    }

    /**
     * Return a string value representing a WorkflowGetPropertiesResponse object.
     *
     * @return string representation of WorkflowGetPropertiesResponse
     */
    @Override
    public String toString() {
        return "WorkflowGetPropertiesResponse{" +
                "workflowName='" + workflowName + '\'' +
                ", workflowKey='" + workflowKey + '\'' +
                ", workflowDescription='" + workflowDescription + '\'' +
                ", workflowID='" + workflowID + '\'' +
                ", workflowVersion='" + workflowVersion + '\'' +
                ", workflowDefinitionFileMD5Value='" + workflowDefinitionFileMD5Value + '\'' +
                ", vendor='" + vendor + '\'' +
                ", owner='" + owner + '\'' +
                ", workflowArchiveSAFID='" + workflowArchiveSAFID + '\'' +
                ", system='" + system + '\'' +
                ", jobsOutputDirectory='" + jobsOutputDirectory + '\'' +
                ", category='" + category + '\'' +
                ", productID='" + productID + '\'' +
                ", productName='" + productName + '\'' +
                ", productVersion='" + productVersion + '\'' +
                ", percentComplete=" + percentComplete +
                ", isCallable=" + isCallable +
                ", containsParallelSteps=" + containsParallelSteps +
                ", scope='" + scope + '\'' +
                ", statusName='" + statusName + '\'' +
                ", deleteCompletedJobs=" + deleteCompletedJobs +
                ", automationStatus=" + automationStatus +
                ", autoDeleteOnCompletion=" + autoDeleteOnCompletion +
                ", access='" + access + '\'' +
                ", accountInfo='" + accountInfo + '\'' +
                ", jobStatement='" + jobStatement + '\'' +
                ", templateID='" + templateID + '\'' +
                ", actionID='" + actionID + '\'' +
                ", registryID='" + registryID + '\'' +
                ", parentRegistryID='" + parentRegistryID + '\'' +
                ", domainID='" + domainID + '\'' +
                ", tenantID='" + tenantID + '\'' +
                ", softwareServiceInstanceName='" + softwareServiceInstanceName + '\'' +
                ", templateName='" + templateName + '\'' +
                ", globalVariableGroup='" + globalVariableGroup + '\'' +
                ", isInstanceVariableWithoutPrefix='" + isInstanceVariableWithoutPrefix + '\'' +
                ", steps=" + steps +
                ", variables=" + variables +
                '}';
    }

}
